# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\x12\x07predict\"\"\n\x0ePredictRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\"4\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\x02\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x91\x01\n\tPredictor\x12<\n\x07Predict\x12\x17.predict.PredictRequest\x1a\x18.predict.PredictResponse\x12\x46\n\rPredictStream\x12\x17.predict.PredictRequest\x1a\x18.predict.PredictResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=26
  _globals['_PREDICTREQUEST']._serialized_end=60
  _globals['_PREDICTRESPONSE']._serialized_start=62
  _globals['_PREDICTRESPONSE']._serialized_end=114
  _globals['_PREDICTOR']._serialized_start=117
  _globals['_PREDICTOR']._serialized_end=262
# @@protoc_insertion_point(module_scope)
